### ISSUE TITLE
VIS Creative Assignment 1 Ready for Grading

### ISSUE THREAD

**Issue by jcmeinhardt** [VIS-2129-F2020/jmeinhardt-vis#1]
Hi Carole and Aleksandar!

Here is the html for my creative assignment:
https://vis-2129-f2020.github.io/jmeinhardt-vis/VIS_Creative_Assigment_1.html

Best,

Julia

**Comment by bauranov** [comment]
Very informative plots, great work overall! You can remove messages from HTML by adding {r, message=FALSE}. In Figure 9, you might think about adding points along with the text. Not a requirement, but when you have longer text, it's not clear where exatly it falls in the coordinate system. You can do that by adding geom_point() after geom_text() - essentially creating a scatter plot and adding labels to each point. Keep up the good work!
