### ISSUE TITLE
VIS Assignment 2 Ready for Grading (Projections and Distortion)

### ISSUE THREAD

**Issue by jcmeinhardt** [VIS-2129-F2020/jmeinhardt-vis#2]
Hi Carole and Aleksander,

Here is my html link for assignment 2: 

https://vis-2129-f2020.github.io/jmeinhardt-vis/VIS_Assignment2.html

I really appreciate the network of spaces you have created for students to get feedback and help on assignments, and that network seems to be growing as students compile resources collaboratively. This has made working in R feel so much less intimidating and more like a collaborative learning environment and exciting medium for exploration and self-growth. I appreciate the thought and consideration that has gone into structuring this course and the relevancy of the skills we are learning. 

Best,

Julia

**Comment by bauranov** [comment]
Hi Julia,
Thanks for the kind words. Here are some comments:
- Nice work on selecting the region in which you have a personal interest, that makes mapping both more fun and more meaningful. I encourage you to continue doing that. Additionally, you showed a dose of skepticism about the quality of data, which is something to think about every time you are doing data analysis/visualization.
- Add an empty row between the end of the code chunk and the text to get the proper formatting (See how cloropleth map and "#### Cartogram" are in the same line in HTML. Hit enter after ``` in R to make it look as it should). 
- Try to experiment with color palettes other than viridis, maybe cartogram and colorpleth will be more readable. 
- When you knit the HTML, go over it and see if there are any messages or warnings you don't want in your final document. If there are, go back to the code chunk displaying the message and add {r, message=FALSE, warning=FALSE}.

Continue exploring your ideas, looking forward to seeing what you do next!
