### ISSUE TITLE
Assignment 3 Ready for Grading 

### ISSUE THREAD

**Issue by jcmeinhardt** [VIS-2129-F2020/jmeinhardt-vis#3]
Hello Carole and Alex!

Here's my html for assignment 3: 

https://vis-2129-f2020.github.io/jmeinhardt-vis/VIS_Assignment3

Best,

Julia

**Comment by bauranov** [comment]
Overall, very good work! Here are some comments:

- The first map is very small, very difficult to see what's going on. You can control the size of the plot by adding fig.width and fig.heigth to {r}, for example, {r, fig.width=10}
- In rmd, add an empty row between the code chunk with the gpplot and the header to get proper formatting in the HTML.
- Make sure the annotation scale and the legend are not overlapping.
